DROP TABLE IF EXISTS path_name;
DROP TABLE IF EXISTS gps_points;

CREATE TABLE path_name (
id INTEGER PRIMARY KEY AUTOINCREMENT,
pathname TEXT UNIQUE NOT NULL,
time_start TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE gps_points (
id INTEGER PRIMARY KEY AUTOINCREMENT,
path_id INTEGER NOT NULL,
time_created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
longitude FLOAT,
latitude FLOAT,
FOREIGN KEY (path_id) REFERENCES path_name (id)
);
